# Development environment specific configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/english_learning
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    flyway:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration
  redis:
    host: localhost
    port: 6379

logging:
  level:
    com.clbboost: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  cors:
    allowed-origins: http://localhost:3000
  security:
    jwt:
      secret: dev_secret_key_should_be_at_least_256_bits_long_for_hs256_algorithm
      secure-cookie: false
  email:
    simulation: true  # Simulates email sending in dev env, logs to console instead